### ISSUE TITLE
Incorrect scrolling through fonts

### ISSUE THREAD

**Issue by annie-elequin** [chiragbhansali/tyffle#1]
### Expected Behaviour
Scrolling to the right through the fonts

### Actual Behaviour
moves the entire page to the left and scrolls into view of the Bookmarks page
-but- I'm loving this little tool, and look forward to using it :)

**Comment by chiragbhansali** [comment]
Thanks for the feedback. Are you experiencing this problem on a mobile? I didn't experience any such behavior on a laptop. On a mobile, you will have to use the navigation buttons that are there in the footer.

**Comment by annie-elequin** [comment]
Nope - it was on a laptop. But I was using firefox, so perhaps that was the issue. I could maybe record my screen and show you what's happening?

________________________________

**Comment by chiragbhansali** [comment]
@annie-mathis : While I try to fix this, you can use the spacebar or 'enter' key to cycle through the fonts. Thanks for reporting the issue.

**Comment by chiragbhansali** [comment]
@annie-mathis : The issue has been fixed and I don't see that problem in Firefox. Let me know if it persists
